=== Buzztrax/buzztrax/docs/buzztard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
get http://xml.fiforms.org/xs3p/ and generate docs
xsltproc -o buzztard.xsd.html /home/ensonic/download/xs3p-1.1.3/xs3p.xsl buzztard.xsd
-->
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.buzztard.org/"
  xmlns="http://www.buzztard.org/"
  elementFormDefault="qualified">

  <!--
  <xsd:attribute name="key" type="xsd:string"/>
  <xsd:attribute name="value" type="xsd:string"/>
  <xsd:attribute name="voice" type="xsd:integer"/>
  <xsd:attribute name="voices" type="xsd:integer"/>
  <xsd:attribute name="id" type="xsd:string"/>
  <xsd:attribute name="type" type="xsd:string"/>
  <xsd:attribute name="index" type="xsd:integer"/>
  <xsd:attribute name="plugin-name" type="xsd:string"/>
  <xsd:attribute name="src" type="xsd:string"/>
  <xsd:attribute name="dst" type="xsd:string"/>
  <xsd:attribute name="gain" type="xsd:float"/>
  <xsd:attribute name="pan" type="xsd:float"/>
  <xsd:attribute name="machine" type="xsd:string"/>
  <xsd:attribute name="length" type="xsd:integer"/>
  <xsd:attribute name="time" type="xsd:integer"/>
  <xsd:attribute name="pattern" type="xsd:string"/>
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="url" type="xsd:string"/>
  <xsd:attribute name="tracks" type="xsd:integer"/>
  <xsd:attribute name="loop" type="xsd:string"/>
  <xsd:attribute name="loop-start" type="xsd:integer"/>
  <xsd:attribute name="loop-end" type="xsd:integer"/>
  -->

  <xsd:element name="info" type="xsd:string"/>
  <xsd:element name="name" type="xsd:string"/>
  <xsd:element name="author" type="xsd:string"/>
  <xsd:element name="genre" type="xsd:string"/>
  <xsd:element name="bpm" type="xsd:integer"/>
  <xsd:element name="tpb" type="xsd:integer"/>
  <xsd:element name="bars" type="xsd:integer"/>
  <xsd:element name="create-dts" type="xsd:dateTime"/>
  <xsd:element name="change-dts" type="xsd:dateTime"/>

  <xsd:element name="meta">
    <xsd:annotation>
      <xsd:documentation>
        Song metadata, like title and genre.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="info" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="genre" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="author" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="create-dts" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="change-dts" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="bpm" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="tpb" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="bars" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wiredata">
    <xsd:annotation>
      <xsd:documentation>
        Pattern data for all voices of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="globaldata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a dynamic parameter of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="prefsdata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a static parameter of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="property">
    <xsd:annotation>
      <xsd:documentation>
        State data.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="key" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="properties">
    <xsd:annotation>
      <xsd:documentation>
        State key-value list.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="property" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="voicedata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a dynamic parameter for one voice of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="voice" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="pattern">
    <xsd:annotation>
      <xsd:documentation>
        Control change fragment for one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="tick" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="id" use="required" type="xsd:string"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="length" use="required" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="patterns">
    <xsd:annotation>
      <xsd:documentation>
        List of control change fragments for one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pattern" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="machine">
    <xsd:annotation>
      <xsd:documentation>
        Media generator/effect/sink.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="prefsdata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="globaldata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="voicedata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="patterns" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="type" use="required" type="xsd:string"/>
      <xsd:attribute name="id" use="required" type="xsd:string"/>
      <xsd:attribute name="plugin-name" type="xsd:string"/>
      <xsd:attribute name="voices"  type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
    
  <xsd:element name="machines">
    <xsd:annotation>
      <xsd:documentation>
        List of machines.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="machine" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wire-pattern">
    <xsd:annotation>
      <xsd:documentation>
        Control change fragment for one wire and pattern.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="tick" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="pattern-id" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="wire-patterns">
    <xsd:annotation>
      <xsd:documentation>
        List of control change fragments for one wire.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wire-pattern" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="wire">
    <xsd:annotation>
      <xsd:documentation>
        Connection of two machines.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="wire-patterns" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="src" use="required" type="xsd:string"/>
      <xsd:attribute name="dst" use="required" type="xsd:string"/>
      <xsd:attribute name="gain" use="required"  type="xsd:float"/>
      <xsd:attribute name="panorama"  type="xsd:float"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wires">
    <xsd:annotation>
      <xsd:documentation>
        List of connections.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wire" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="setup">
    <xsd:annotation>
      <xsd:documentation>
        Virtual gear setup (machines and wires).
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="machines" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="wires" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="tick">
    <xsd:annotation>
      <xsd:documentation>
        Time slot.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="voicedata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="globaldata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="wiredata" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="label">
    <xsd:annotation>
      <xsd:documentation>
        Annotation for a tick.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="labels">
    <xsd:annotation>
      <xsd:documentation>
        List of annotations.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="position">
    <xsd:annotation>
      <xsd:documentation>
        Time location for a pattern in a track.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
      <xsd:attribute name="pattern" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="track">
    <xsd:annotation>
      <xsd:documentation>
        Slot for pattern related to one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="position" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    <xsd:attribute name="index" use="required" type="xsd:integer"/>
    <xsd:attribute name="machine" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="tracks">
    <xsd:annotation>
      <xsd:documentation>
        List of tracks.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="track" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="sequence">
    <xsd:annotation>
      <xsd:documentation>
        Song structure build of a timeline and tracks.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="labels" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="tracks" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="length" use="required" type="xsd:integer"/>
      <xsd:attribute name="tracks" use="required" type="xsd:integer"/>
      <xsd:attribute name="loop" use="optional" type="xsd:string"/>
      <xsd:attribute name="loop-start" use="optional" type="xsd:integer"/>
      <xsd:attribute name="loop-end" use="optional" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wave">
    <xsd:annotation>
      <xsd:documentation>
        Wave in a wavetable.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="index" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="uri" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wavetable">
    <xsd:annotation>
      <xsd:documentation>
        List of waves.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wave" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="buzztard">
    <xsd:annotation>
      <xsd:documentation>
        Toplevel elements for a buzztard song.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="meta" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="setup" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="sequence" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="wavetable" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Buzztrax/buzztrax/tests/songs/test-simple5.xml
<?xml version="1.0"?>
<buzztard xmlns="http://www.buzztard.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="buzztard.xsd">
  <meta>
    <info>what a lovely tune</info>
    <name>test simple 5</name>
    <genre>dark-wave</genre>
    <author>Stefan Kost</author>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2008-04-06T12:58:20Z</change-dts>
    <bpm>100</bpm>
    <tpb>8</tpb>
    <bars>16</bars>
  </meta>
  <setup>
    <properties>
      <property key="ypos" value="168.51658593378852"/>
      <property key="active-page" value="0"/>
    </properties>
    <machines>
      <machine id="audio_sink" type="sink">
        <properties>
          <property key="ypos" value="0.5"/>
          <property key="xpos" value="0.7"/>
        </properties>
        <globaldata name="master-volume" value="1"/>
        <patterns>
          <pattern id="audio_sink 00" name="00" length="16">
            <tick time="0">
              <globaldata name="master-volume" value="0.62500953688868544"/>
            </tick>
            <tick time="15">
              <globaldata name="master-volume" value="10.000152590218967"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
      <machine id="amp1" type="processor" plugin-name="volume" voices="0">
        <properties>
          <property key="ypos" value="0.0"/>
          <property key="xpos" value="0.3"/>
        </properties>
        <globaldata name="mute" value="0"/>
        <globaldata name="volume" value="1"/>
      </machine>
      <machine id="sine1" type="source" plugin-name="audiotestsrc" voices="0">
        <properties>
          <property key="ypos" value="0.5"/>
          <property key="xpos" value="0.0"/>
        </properties>
        <globaldata name="wave" value="0"/>
        <globaldata name="freq" value="440"/>
        <globaldata name="volume" value="0.10000000000000001"/>
        <patterns>
          <pattern id="sine1_beep" name="beeps" length="3">
            <tick time="0">
              <globaldata name="freq" value="440"/>
            </tick>
            <tick time="1">
              <globaldata name="freq" value="880"/>
            </tick>
            <tick time="2">
              <globaldata name="freq" value="1760"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
      <machine id="sine2" type="source" plugin-name="audiotestsrc" voices="0">
        <properties>
          <property key="ypos" value="0.0"/>
          <property key="xpos" value="0.0"/>
        </properties>
        <globaldata name="wave" value="0"/>
        <globaldata name="freq" value="440"/>
        <globaldata name="volume" value="0.10000000000000001"/>
        <patterns>
          <pattern id="sine2_beep" name="beeps" length="8">
            <tick time="0">
              <globaldata name="freq" value="110"/>
            </tick>
            <tick time="2">
              <globaldata name="freq" value="220"/>
            </tick>
            <tick time="6">
              <globaldata name="freq" value="55"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
      <machine id="volume" type="processor" plugin-name="volume" voices="0">
        <properties>
          <property key="ypos" value="0.69333333333333336"/>
          <property key="xpos" value="0.32000000000000001"/>
        </properties>
        <globaldata name="mute" value="0"/>
        <globaldata name="volume" value="1"/>
      </machine>
    </machines>
    <wires>
      <wire src="sine1" dst="amp1" gain="1.5"/>
      <wire src="sine2" dst="amp1" gain="0.5"/>
      <wire src="amp1" dst="audio_sink" gain="1" panorama="0">
        <patterns>
          <pattern id="audio_sink 00">
            <tick time="0">
              <wiredata name="panorama" value="-1"/>
            </tick>
            <tick time="7">
              <wiredata name="panorama" value="-0.87499809265136719"/>
            </tick>
            <tick time="15">
              <wiredata name="panorama" value="-0.74999618530273438"/>
            </tick>
          </pattern>
        </patterns>
      </wire>
      <wire src="sine1" dst="volume" gain="1"/>
      <wire src="volume" dst="audio_sink" gain="1" panorama="0"/>
    </wires>
  </setup>
  <sequence length="16" tracks="2">
    <labels>
      <label name="start" time="0"/>
    </labels>
    <tracks>
      <track index="0" machine="sine1">
        <position time="0" pattern="sine1_beep"/>
      </track>
      <track index="1" machine="sine2">
        <position time="0" pattern="sine2_beep"/>
      </track>
    </tracks>
  </sequence>
</buzztard>

=== Buzztrax/buzztrax/tests/songs/simple1.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard xmlns="http://buzztard.sourceforge.net/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="buzztard.xsd"
	name="example Song">

	<meta>
		<info>what a lovely tune</info>
		<genre>dark-wave</genre>
	</meta>
	
  <setup zoom="1.0">    
    <machines>
      <sink id="audio_sink" pluginname="esdsink">
        <machineui xpos="20" ypos="10"/>
        <globaldata name="volume" value="20"/>
        <globaldata name="bpm" value="145"/>
      </sink>
      
      <processor id="amp1" pluginname="volume">
        <machineui xpos="50" ypos="30"/>
      </processor>
      
      <source id="sine1" pluginname="sinesrc" voices="0">
        <machineui xpos="20" ypos="80"/>
        <globaldata name="volume" value="1.0"/>
      </source>
    </machines>
    
    <wires>
      <wire src="sine1" dst="amp1" gain="1.5"/>
      <wire src="amp1" dst="audio_sink" gain="1.0" pan="-50"/>
    </wires>    
  </setup>
  
  <patterns>
    <pattern id="sine1_beep" machine="sine1" name="beeps" length="8">
      <tick time="0">
        <globaldata name="freq" value="440"/>
				<globaldata name="volume" value="1.0"/>
      </tick>
      <tick time="2">
        <globaldata name="freq" value="880"/>
				<globaldata name="volume" value="1.0"/>
      </tick>
      <tick time="4">
        <globaldata name="freq" value="1760"/>
				<globaldata name="volume" value="1.0"/>
      </tick>
    </pattern>
  </patterns>
  
  <sequence>
    <labels>
      <label time="0" name="start"/>
      <label time="9" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="sine1">
        <position time="0" pattern="sine1_beep"/>
        <position time="3" pattern="sine1_beep"/>
      </track>
    </tracks>
  </sequence>
  
  <wavetable/>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/buzz6.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
	xmlns="http://www.buzztard.org/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:noNamespaceSchemaLocation="buzztard.xsd">

	<meta>
		<info>three buzz generators</info>
	    <name>buzz 6</name>
		<genre>dark-wave</genre>
    	<bpm>120</bpm>
	    <tpb>4</tpb>
    	<bars>16</bars>
	</meta>
	
  <setup zoom="1.0">
    <machines>
      <sink id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <globaldata name="volume" value="20"/>
        <globaldata name="bpm" value="145"/>
      </sink>
      
      <source id="bd" pluginname="bml-ErsKick" voices="1">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
      </source>

      <source id="snr" pluginname="bml-ErsSnare" voices="1">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
      </source>

    <source id="hh" pluginname="bml-ErsHihat" voices="1">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
      </source>
    </machines>
    
    <wires>
      <wire src="bd" dst="audio_sink" gain="1.0" pan="-50"/>
      <wire src="snr" dst="audio_sink" gain="1.0" pan="-50"/>
      <wire src="hh" dst="audio_sink" gain="1.0" pan="-50"/>
    </wires>    
  </setup>
  
  <patterns>
    <pattern id="bd_beats" machine="bd" name="beats" length="16">
      <tick time= "0"><voicedata name="Trig" voice="0" value="1"/></tick>
      <tick time= "4"><voicedata name="Trig" voice="0" value="1"/></tick>
      <tick time= "8"><voicedata name="Trig" voice="0" value="1"/></tick>
      <tick time="12"><voicedata name="Trig" voice="0" value="1"/></tick>
    </pattern>
    <pattern id="snr_beats" machine="snr" name="beats" length="16">
      <tick time= "4"><voicedata name="Trig" voice="0" value="1"/></tick>
      <tick time="12"><voicedata name="Trig" voice="0" value="1"/></tick>
    </pattern>
  </patterns>
  
  <sequence>
    <labels>
      <label time="0" name="start"/>
      <label time="63" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="bd">
        <position time="0" pattern="bd_beats"/>
        <position time="32" pattern="bd_beats"/>
      </track>
      <track index="1" machine="snr">
        <position time="0" pattern="snr_beats"/>
        <position time="16" pattern="snr_beats"/>
        <position time="32" pattern="snr_beats"/>
        <position time="48" pattern="snr_beats"/>
      </track>
    </tracks>
  </sequence>
  
  <wavetable/>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/test-simple3.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>what a lovely tune</info>
    <name>test simple 3</name>
    <genre>dark-wave</genre>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2005-09-20T22:10:56Z</change-dts>
    <bpm>100</bpm>
    <tpb>8</tpb>
    <bars>16</bars>
  </meta>

  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
      </machine>

      <machine type="processor" id="amp1" plugin-name="volume">
        <properties>
          <property key="xpos" value="0.3"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
      </machine>

      <machine type="source" id="sine1" plugin-name="audiotestsrc" voices="0">
        <properties>
          <property key="xpos" value="0.0"/>
          <property key="ypos" value="0.5"/>
        </properties>
        <globaldata name="volume" value="0.1"/>
        <patterns>
          <pattern id="sine1_beep" name="beeps" length="3">
            <tick time="0">
              <globaldata name="freq" value="440.0"/>
            </tick>
            <tick time="1">
              <globaldata name="freq" value="880.0"/>
            </tick>
            <tick time="2">
              <globaldata name="freq" value="1760.0"/>
            </tick>
          </pattern>
        </patterns>
      </machine>

      <machine type="source" id="sine2" plugin-name="audiotestsrc" voices="0">
        <properties>
          <property key="xpos" value="0.0"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <globaldata name="volume" value="0.1"/>
        <patterns>
          <pattern id="sine2_beep" name="beeps" length="8">
            <tick time="0">
              <globaldata name="freq" value="110.0"/>
            </tick>
            <tick time="2">
              <globaldata name="freq" value="220.0"/>
            </tick>
            <tick time="6">
              <globaldata name="freq" value="55.0"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
    </machines>

    <wires>
      <wire src="sine1" dst="amp1" gain="1.5"/>
      <wire src="sine2" dst="amp1" gain="0.5"/>
      <wire src="amp1" dst="audio_sink" gain="1.0" panorama="-0.5"/>
    </wires>
  </setup>

  <sequence length="16" tracks="2">
    <labels>
      <label time="0" name="start"/>
      <!--label time="1" name="end"/-->
    </labels>
    <tracks>
      <track index="0" machine="sine1">
        <position time="0" pattern="sine1_beep"/>
      </track>
      <track index="1" machine="sine2">
        <position time="0" pattern="sine2_beep"/>
      </track>
    </tracks>
  </sequence>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/buzz8.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>one buzz generator and one buzz effect</info>
      <name>buzz 8</name>
    <genre>dark-wave</genre>
      <bpm>120</bpm>
      <tpb>4</tpb>
      <bars>16</bars>
  </meta>
  
  <setup zoom="1.0">
    <machines>
      <sink id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
        <globaldata name="volume" value="20"/>
        <globaldata name="bpm" value="145"/>
      </sink>

      <processor id="delay1" plugin-name="bml-Ninja" voices="1">
        <properties>
          <property key="xpos" value="0.0"/>
          <property key="ypos" value="0.0"/>
        </properties>
      </processor>

      <source id="gen" plugin-name="bml-GoaKick" voices="0">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
      </source>
    </machines>
    
    <wires>
      <wire src="gen" dst="delay1" gain="1.0" pan="0"/>
      <wire src="delay1" dst="audio_sink" gain="1.0" pan="0"/>
    </wires>    
  </setup>
  
  <patterns>
    <pattern id="gen_beats" machine="gen" name="beats" length="16">
      <tick time="0">
        <globaldata name="Trigger" value="10"/>
        <globaldata name="Tone" value="40"/>
      </tick>
      <tick time="4"><globaldata name="Trigger" value="40"/></tick>
      <tick time="8"><globaldata name="Trigger" value="80"/></tick>
    </pattern>
  </patterns>
  
  <sequence>
    <labels>
      <label time="0" name="start"/>
      <label time="95" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="gen">
        <position time="0" pattern="gen_beats"/>
        <position time="32" pattern="gen_beats"/>
        <position time="48" pattern="gen_beats"/>
        <position time="64" pattern="gen_beats"/>
        <position time="80" pattern="gen_beats"/>
      </track>
    </tracks>
  </sequence>
  
  <wavetable/>

</buzztard>
