=== Buzztrax/buzztrax/docs/buzztard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
get http://xml.fiforms.org/xs3p/ and generate docs
xsltproc -o buzztard.xsd.html /home/ensonic/download/xs3p-1.1.3/xs3p.xsl buzztard.xsd
-->
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.buzztard.org/"
  xmlns="http://www.buzztard.org/"
  elementFormDefault="qualified">

  <!--
  <xsd:attribute name="key" type="xsd:string"/>
  <xsd:attribute name="value" type="xsd:string"/>
  <xsd:attribute name="voice" type="xsd:integer"/>
  <xsd:attribute name="voices" type="xsd:integer"/>
  <xsd:attribute name="id" type="xsd:string"/>
  <xsd:attribute name="type" type="xsd:string"/>
  <xsd:attribute name="index" type="xsd:integer"/>
  <xsd:attribute name="plugin-name" type="xsd:string"/>
  <xsd:attribute name="src" type="xsd:string"/>
  <xsd:attribute name="dst" type="xsd:string"/>
  <xsd:attribute name="gain" type="xsd:float"/>
  <xsd:attribute name="pan" type="xsd:float"/>
  <xsd:attribute name="machine" type="xsd:string"/>
  <xsd:attribute name="length" type="xsd:integer"/>
  <xsd:attribute name="time" type="xsd:integer"/>
  <xsd:attribute name="pattern" type="xsd:string"/>
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="url" type="xsd:string"/>
  <xsd:attribute name="tracks" type="xsd:integer"/>
  <xsd:attribute name="loop" type="xsd:string"/>
  <xsd:attribute name="loop-start" type="xsd:integer"/>
  <xsd:attribute name="loop-end" type="xsd:integer"/>
  -->

  <xsd:element name="info" type="xsd:string"/>
  <xsd:element name="name" type="xsd:string"/>
  <xsd:element name="author" type="xsd:string"/>
  <xsd:element name="genre" type="xsd:string"/>
  <xsd:element name="bpm" type="xsd:integer"/>
  <xsd:element name="tpb" type="xsd:integer"/>
  <xsd:element name="bars" type="xsd:integer"/>
  <xsd:element name="create-dts" type="xsd:dateTime"/>
  <xsd:element name="change-dts" type="xsd:dateTime"/>

  <xsd:element name="meta">
    <xsd:annotation>
      <xsd:documentation>
        Song metadata, like title and genre.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="info" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="genre" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="author" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="create-dts" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="change-dts" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="bpm" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="tpb" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="bars" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wiredata">
    <xsd:annotation>
      <xsd:documentation>
        Pattern data for all voices of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="globaldata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a dynamic parameter of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="prefsdata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a static parameter of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="property">
    <xsd:annotation>
      <xsd:documentation>
        State data.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="key" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="properties">
    <xsd:annotation>
      <xsd:documentation>
        State key-value list.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="property" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="voicedata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a dynamic parameter for one voice of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="voice" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="pattern">
    <xsd:annotation>
      <xsd:documentation>
        Control change fragment for one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="tick" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="id" use="required" type="xsd:string"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="length" use="required" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="patterns">
    <xsd:annotation>
      <xsd:documentation>
        List of control change fragments for one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pattern" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="machine">
    <xsd:annotation>
      <xsd:documentation>
        Media generator/effect/sink.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="prefsdata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="globaldata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="voicedata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="patterns" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="type" use="required" type="xsd:string"/>
      <xsd:attribute name="id" use="required" type="xsd:string"/>
      <xsd:attribute name="plugin-name" type="xsd:string"/>
      <xsd:attribute name="voices"  type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
    
  <xsd:element name="machines">
    <xsd:annotation>
      <xsd:documentation>
        List of machines.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="machine" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wire-pattern">
    <xsd:annotation>
      <xsd:documentation>
        Control change fragment for one wire and pattern.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="tick" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="pattern-id" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="wire-patterns">
    <xsd:annotation>
      <xsd:documentation>
        List of control change fragments for one wire.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wire-pattern" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="wire">
    <xsd:annotation>
      <xsd:documentation>
        Connection of two machines.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="wire-patterns" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="src" use="required" type="xsd:string"/>
      <xsd:attribute name="dst" use="required" type="xsd:string"/>
      <xsd:attribute name="gain" use="required"  type="xsd:float"/>
      <xsd:attribute name="panorama"  type="xsd:float"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wires">
    <xsd:annotation>
      <xsd:documentation>
        List of connections.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wire" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="setup">
    <xsd:annotation>
      <xsd:documentation>
        Virtual gear setup (machines and wires).
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="machines" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="wires" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="tick">
    <xsd:annotation>
      <xsd:documentation>
        Time slot.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="voicedata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="globaldata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="wiredata" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="label">
    <xsd:annotation>
      <xsd:documentation>
        Annotation for a tick.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="labels">
    <xsd:annotation>
      <xsd:documentation>
        List of annotations.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="position">
    <xsd:annotation>
      <xsd:documentation>
        Time location for a pattern in a track.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
      <xsd:attribute name="pattern" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="track">
    <xsd:annotation>
      <xsd:documentation>
        Slot for pattern related to one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="position" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    <xsd:attribute name="index" use="required" type="xsd:integer"/>
    <xsd:attribute name="machine" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="tracks">
    <xsd:annotation>
      <xsd:documentation>
        List of tracks.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="track" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="sequence">
    <xsd:annotation>
      <xsd:documentation>
        Song structure build of a timeline and tracks.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="labels" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="tracks" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="length" use="required" type="xsd:integer"/>
      <xsd:attribute name="tracks" use="required" type="xsd:integer"/>
      <xsd:attribute name="loop" use="optional" type="xsd:string"/>
      <xsd:attribute name="loop-start" use="optional" type="xsd:integer"/>
      <xsd:attribute name="loop-end" use="optional" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wave">
    <xsd:annotation>
      <xsd:documentation>
        Wave in a wavetable.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="index" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="uri" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wavetable">
    <xsd:annotation>
      <xsd:documentation>
        List of waves.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wave" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="buzztard">
    <xsd:annotation>
      <xsd:documentation>
        Toplevel elements for a buzztard song.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="meta" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="setup" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="sequence" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="wavetable" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Buzztrax/buzztrax/tests/songs/buzz7.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>three buzz generators and one buzz effect</info>
      <name>buzz 7</name>
      <genre>dark-wave</genre>
      <bpm>120</bpm>
      <tpb>4</tpb>
      <bars>16</bars>
      <create-dts>2005-09-20T22:10:56Z</create-dts>
      <change-dts>2005-09-20T22:10:56Z</change-dts>
  </meta>
  
  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <globaldata name="volume" value="20"/>
        <globaldata name="bpm" value="145"/>
      </machine>

      <machine type="processor" id="chorus" plugin-name="bml-Jeskola-Chorus" voices="0">
        <properties>
          <property key="xpos" value="0.0"/>
          <property key="ypos" value="0.0"/>
        </properties>
      </machine>

      <machine type="source" id="bd" plugin-name="bml-ErsKick" voices="1">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
        <patterns>
          <pattern id="bd_beats" machine="bd" name="beats" length="16">
            <tick time= "0"><voicedata name="Trig" voice="0" value="1"/></tick>
            <tick time= "4"><voicedata name="Trig" voice="0" value="1"/></tick>
            <tick time= "8"><voicedata name="Trig" voice="0" value="1"/></tick>
            <tick time="12"><voicedata name="Trig" voice="0" value="1"/></tick>
          </pattern>
        </patterns>
      </machine>

      <machine type="source" id="snr" plugin-name="bml-ErsSnare" voices="1">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
        <patterns>
          <pattern id="snr_beats" machine="snr" name="beats" length="16">
            <tick time= "4"><voicedata name="Trig" voice="0" value="1"/></tick>
            <tick time="12"><voicedata name="Trig" voice="0" value="1"/></tick>
          </pattern>
        </patterns>
      </machine>

      <machine type="source" id="hh" plugin-name="bml-ErsHihat" voices="1">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
      </machine>
    </machines>
    
    <wires>
      <wire src="chorus" dst="audio_sink" gain="1.0" pan="0"/>
      <wire src="bd" dst="chorus" gain="1.0" pan="-50"/>
      <wire src="snr" dst="chorus" gain="1.0" pan="-50"/>
      <wire src="hh" dst="chorus" gain="1.0" pan="-50"/>
    </wires>    
  </setup>
  
  <sequence length="64" tracks="2">
    <labels>
      <label time="0" name="start"/>
      <label time="63" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="bd">
        <position time="0" pattern="bd_beats"/>
        <position time="32" pattern="bd_beats"/>
      </track>
      <track index="1" machine="snr">
        <position time="0" pattern="snr_beats"/>
        <position time="16" pattern="snr_beats"/>
        <position time="32" pattern="snr_beats"/>
        <position time="48" pattern="snr_beats"/>
      </track>
    </tracks>
  </sequence>
  
</buzztard>

=== Buzztrax/buzztrax/tests/songs/broken2.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>this song misses external files</info>
    <name>broken 2</name>
    <genre>trash</genre>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2005-09-20T22:10:56Z</change-dts>
    <bpm>100</bpm>
    <tpb>8</tpb>
    <bars>16</bars>
  </meta>
  
  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
      </machine>
      
      <machine type="source" id="missing1" plugin-name="missingsrc" voices="0">
        <patterns>
          <pattern name="melo" length="3">
            <tick time="0">
              <voicedata name="freq" voice="0" value="440,0"/>
              <voicedata name="volume" voice="0" value="1,0"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
    </machines>
    
    <wires>
      <wire src="missing1" dst="audio_sink" gain="1.0"/>
    </wires>
  </setup>
  
  <sequence length="16" tracks="1">
    <labels>
      <label time="0" name="start"/>
      <!--label time="1" name="end"/-->
    </labels>
    <tracks>
      <track index="0" machine="missing1">
        <position time="0" pattern="melo"/>
      </track>
    </tracks>
  </sequence>

  <wavetable>
    <!-- loading file from harddisk -->
    <wave index="1" name="909base" uri="file:///data/samples/basedrums/909base.wav"/>
    <!-- loading file from song archive -->
    <wave index="2" name="dreampad" uri="file://!/wavetable/dreampad.wav"/>
  </wavetable>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/melo6.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>a three voice melody and hihats</info>
    <name>melo 6</name>
    <genre>chip-music</genre>
    <create-dts>2011-10-04T21:44:56Z</create-dts>
    <change-dts>2011-10-04T21:44:56Z</change-dts>
    <bpm>120</bpm>
    <tpb>4</tpb>
    <bars>16</bars>
  </meta>
  
  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.0"/>
        </properties>
      </machine>
            
      <machine type="source" id="beep1" plugin-name="simsyn" voices="0">
        <globaldata name="volume" value="1.0"/>
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <patterns>
          <pattern id="beep1::C-4_E-4_G-4" name="C-4_E-4_G-4" length="16">
            <tick time="0">
              <globaldata name="note" value="c-4"/>
              <globaldata name="volume" value="0.85"/>
              <globaldata name="decay" value="0.25"/>
              <globaldata name="wave" value="3"/>
            </tick>
            <tick time="8">
              <globaldata name="note" value="e-4"/>
            </tick>
            <tick time="12">
              <globaldata name="note" value="g-4"/>
            </tick>
          </pattern>
        </patterns>
      </machine>

      <machine type="source" id="beep2" plugin-name="simsyn" voices="0">
        <globaldata name="volume" value="1.0"/>
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <patterns>
          <pattern id="beep2::C-1" name="C-1" length="16">
            <tick time="0">
              <globaldata name="note" value="c-1"/>
              <globaldata name="volume" value="0.4"/>
              <globaldata name="decay" value="1.0"/>
              <globaldata name="wave" value="2"/>
            </tick>
          </pattern>
        </patterns>
      </machine>

      <machine type="source" id="beep3" plugin-name="simsyn" voices="0">
        <globaldata name="volume" value="1.0"/>
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
        <patterns>
          <pattern id="beep3::C-2_C-3" name="C-2_C-3" length="16">
            <tick time="0">
              <globaldata name="note" value="c-2"/>
              <globaldata name="volume" value="1.0"/>
              <globaldata name="decay" value="0.15"/>
              <globaldata name="wave" value="2"/>
              <globaldata name="filter" value="1"/>
              <globaldata name="cut-off" value="0.05"/>
              <globaldata name="resonance" value="1.5"/>
            </tick>
            <tick time="2">
              <globaldata name="note" value="c-3"/>
              <globaldata name="cut-off" value="0.1"/>
            </tick>
            <tick time="6">
              <globaldata name="note" value="c-2"/>
              <globaldata name="volume" value="0.7"/>
              <globaldata name="cut-off" value="0.15"/>
              <globaldata name="resonance" value="1.0"/>
            </tick>
            <tick time="6">
              <globaldata name="note" value="c-3"/>
              <globaldata name="cut-off" value="0.2"/>
            </tick>
            <tick time="8">
              <globaldata name="note" value="c-2"/>
              <globaldata name="volume" value="1.0"/>
              <globaldata name="cut-off" value="0.25"/>
              <globaldata name="resonance" value="0.7"/>
            </tick>
            <tick time="10">
              <globaldata name="note" value="c-3"/>
              <globaldata name="cut-off" value="0.3"/>
            </tick>
            <tick time="12">
              <globaldata name="note" value="c-2"/>
              <globaldata name="volume" value="0.7"/>
              <globaldata name="cut-off" value="0.35"/>
              <globaldata name="resonance" value="0.7"/>
            </tick>
            <tick time="14">
              <globaldata name="note" value="c-3"/>
              <globaldata name="cut-off" value="0.4"/>
            </tick>
            <tick time="15">
              <globaldata name="note" value="c-4"/>
              <globaldata name="cut-off" value="0.45"/>
              <globaldata name="resonance" value="0.85"/>
            </tick>
          </pattern>
        </patterns>
      </machine>

      <machine type="processor" id="echo1" plugin-name="audiodelay" voices="0">
        <globaldata name="delaytime" value="25.0"/>
        <globaldata name="feedback" value="75.0"/>
        <globaldata name="drywet" value="50.0"/>
        <properties>
          <property key="xpos" value="0.0"/>
          <property key="ypos" value="-0.5"/>
        </properties>
      </machine>

      <machine type="source" id="hihat" plugin-name="simsyn" voices="0">
        <globaldata name="wave" value="5"/>
        <globaldata name="volume" value="0.6"/>
        <globaldata name="decay" value="0.3"/>
        <globaldata name="filter" value="2"/>
        <globaldata name="cut-off" value="0.8"/>
        <globaldata name="resonance" value="0.7"/>
        <properties>
          <property key="ypos" value="0.5"/>
          <property key="xpos" value="0.0"/>
        </properties>
        <patterns>
          <pattern id="hihat_hats" name="hats" length="16">
            <tick time="2">
              <globaldata name="note" value="c-4"/>
              <globaldata name="decay" value="0.1"/>
            </tick>
            <tick time="6">
              <globaldata name="note" value="c-4"/>
            </tick>
            <tick time="8">
              <globaldata name="note" value="c-4"/>
              <globaldata name="decay" value="0.35"/>
            </tick>
            <tick time="10">
              <globaldata name="note" value="c-4"/>
              <globaldata name="decay" value="0.1"/>
            </tick>
            <tick time="12">
              <globaldata name="note" value="c-3"/>
              <globaldata name="decay" value="0.02"/>
            </tick>
            <tick time="14">
              <globaldata name="note" value="c-4"/>
              <globaldata name="decay" value="0.1"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
    </machines>
    
    <wires>
      <wire src="beep1" dst="echo1" gain="1.0"/>
      <wire src="echo1" dst="audio_sink" gain="1.0"/>
      <wire src="beep2" dst="audio_sink" gain="1.0" panorama="-0.5"/>
      <wire src="beep3" dst="audio_sink" gain="1.0" panorama="+0.5"/>
      <wire src="hihat" dst="audio_sink" gain="1.0"/>
    </wires>
  </setup>
  
  <sequence loop="off" length="100" tracks="6">
    <labels>
      <label time="0" name="start"/>
      <label time="79" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="beep1">
        <position time="0" pattern="beep1::C-4_E-4_G-4"/>
        <position time="32" pattern="beep1::C-4_E-4_G-4"/>
      </track>
      <track index="1" machine="beep2">
        <position time="0" pattern="beep2::C-1"/>
        <position time="16" pattern="beep2::C-1"/>
        <position time="32" pattern="beep2::C-1"/>
        <position time="48" pattern="beep2::C-1"/>
      </track>
      <track index="2" machine="beep3">
        <position time="0" pattern="beep3::C-2_C-3"/>
        <position time="16" pattern="beep3::C-2_C-3"/>
        <position time="32" pattern="beep3::C-2_C-3"/>
        <position time="48" pattern="beep3::C-2_C-3"/>
        <position time="64" pattern="beep3::C-2_C-3"/>
        <position time="80" pattern="beep3::C-2_C-3"/>
      </track>
      <track index="3" machine="echo1"/>
      <track index="4" machine="hihat">
        <position time="16" pattern="hihat_hats"/>
        <position time="32" pattern="hihat_hats"/>
        <position time="48" pattern="hihat_hats"/>
        <position time="64" pattern="hihat_hats"/>
      </track>
      <track index="5" machine="audio_sink"/>
    </tracks>
  </sequence>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/test-simple2.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard xmlns="http://buzztard.sourceforge.net/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="buzztard.xsd"
	name="simple test Song">

	<meta>
		<info>what a lovely tune</info>
    <name>test simple 2</name>
		<genre>dark-wave</genre>
    <bpm>100</bpm>
    <tpb>8</tpb>
    <bars>16</bars>
	</meta>
	
  <setup>
    <machines>
      <sink id="audio_sink">
      </sink>
      <source id="sine1" pluginname="sinesrc" voices="0">
      </source>
    </machines>
    
    <wires>
      <wire src="sine1" dst="audio_sink" gain="1.0"/>
    </wires>    
  </setup>
  
  <patterns>
  </patterns>
  
  <sequence>
    <labels>
      <label time="0" name="start"/>
      <!--label time="1" name="end"/-->
    </labels>
    <tracks>
      <track index="0" machine="sine1">
      </track>
    </tracks>
  </sequence>
  
  <wavetable/>

</buzztard>
