=== Buzztrax/buzztrax/docs/buzztard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
get http://xml.fiforms.org/xs3p/ and generate docs
xsltproc -o buzztard.xsd.html /home/ensonic/download/xs3p-1.1.3/xs3p.xsl buzztard.xsd
-->
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.buzztard.org/"
  xmlns="http://www.buzztard.org/"
  elementFormDefault="qualified">

  <!--
  <xsd:attribute name="key" type="xsd:string"/>
  <xsd:attribute name="value" type="xsd:string"/>
  <xsd:attribute name="voice" type="xsd:integer"/>
  <xsd:attribute name="voices" type="xsd:integer"/>
  <xsd:attribute name="id" type="xsd:string"/>
  <xsd:attribute name="type" type="xsd:string"/>
  <xsd:attribute name="index" type="xsd:integer"/>
  <xsd:attribute name="plugin-name" type="xsd:string"/>
  <xsd:attribute name="src" type="xsd:string"/>
  <xsd:attribute name="dst" type="xsd:string"/>
  <xsd:attribute name="gain" type="xsd:float"/>
  <xsd:attribute name="pan" type="xsd:float"/>
  <xsd:attribute name="machine" type="xsd:string"/>
  <xsd:attribute name="length" type="xsd:integer"/>
  <xsd:attribute name="time" type="xsd:integer"/>
  <xsd:attribute name="pattern" type="xsd:string"/>
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="url" type="xsd:string"/>
  <xsd:attribute name="tracks" type="xsd:integer"/>
  <xsd:attribute name="loop" type="xsd:string"/>
  <xsd:attribute name="loop-start" type="xsd:integer"/>
  <xsd:attribute name="loop-end" type="xsd:integer"/>
  -->

  <xsd:element name="info" type="xsd:string"/>
  <xsd:element name="name" type="xsd:string"/>
  <xsd:element name="author" type="xsd:string"/>
  <xsd:element name="genre" type="xsd:string"/>
  <xsd:element name="bpm" type="xsd:integer"/>
  <xsd:element name="tpb" type="xsd:integer"/>
  <xsd:element name="bars" type="xsd:integer"/>
  <xsd:element name="create-dts" type="xsd:dateTime"/>
  <xsd:element name="change-dts" type="xsd:dateTime"/>

  <xsd:element name="meta">
    <xsd:annotation>
      <xsd:documentation>
        Song metadata, like title and genre.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="info" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="genre" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="author" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="create-dts" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="change-dts" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="bpm" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="tpb" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="bars" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wiredata">
    <xsd:annotation>
      <xsd:documentation>
        Pattern data for all voices of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="globaldata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a dynamic parameter of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="prefsdata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a static parameter of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="property">
    <xsd:annotation>
      <xsd:documentation>
        State data.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="key" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="properties">
    <xsd:annotation>
      <xsd:documentation>
        State key-value list.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="property" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="voicedata">
    <xsd:annotation>
      <xsd:documentation>
        Value of a dynamic parameter for one voice of a machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="voice" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="pattern">
    <xsd:annotation>
      <xsd:documentation>
        Control change fragment for one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="tick" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="id" use="required" type="xsd:string"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="length" use="required" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="patterns">
    <xsd:annotation>
      <xsd:documentation>
        List of control change fragments for one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pattern" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="machine">
    <xsd:annotation>
      <xsd:documentation>
        Media generator/effect/sink.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="prefsdata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="globaldata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="voicedata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="patterns" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="type" use="required" type="xsd:string"/>
      <xsd:attribute name="id" use="required" type="xsd:string"/>
      <xsd:attribute name="plugin-name" type="xsd:string"/>
      <xsd:attribute name="voices"  type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
    
  <xsd:element name="machines">
    <xsd:annotation>
      <xsd:documentation>
        List of machines.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="machine" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wire-pattern">
    <xsd:annotation>
      <xsd:documentation>
        Control change fragment for one wire and pattern.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="tick" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="pattern-id" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="wire-patterns">
    <xsd:annotation>
      <xsd:documentation>
        List of control change fragments for one wire.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wire-pattern" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="wire">
    <xsd:annotation>
      <xsd:documentation>
        Connection of two machines.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="wire-patterns" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="src" use="required" type="xsd:string"/>
      <xsd:attribute name="dst" use="required" type="xsd:string"/>
      <xsd:attribute name="gain" use="required"  type="xsd:float"/>
      <xsd:attribute name="panorama"  type="xsd:float"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wires">
    <xsd:annotation>
      <xsd:documentation>
        List of connections.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wire" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="setup">
    <xsd:annotation>
      <xsd:documentation>
        Virtual gear setup (machines and wires).
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="properties" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="machines" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="wires" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="tick">
    <xsd:annotation>
      <xsd:documentation>
        Time slot.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="voicedata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="globaldata" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="wiredata" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="label">
    <xsd:annotation>
      <xsd:documentation>
        Annotation for a tick.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="labels">
    <xsd:annotation>
      <xsd:documentation>
        List of annotations.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="position">
    <xsd:annotation>
      <xsd:documentation>
        Time location for a pattern in a track.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="time" use="required" type="xsd:integer"/>
      <xsd:attribute name="pattern" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="track">
    <xsd:annotation>
      <xsd:documentation>
        Slot for pattern related to one machine.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="position" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    <xsd:attribute name="index" use="required" type="xsd:integer"/>
    <xsd:attribute name="machine" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="tracks">
    <xsd:annotation>
      <xsd:documentation>
        List of tracks.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="track" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="sequence">
    <xsd:annotation>
      <xsd:documentation>
        Song structure build of a timeline and tracks.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="labels" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="tracks" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="length" use="required" type="xsd:integer"/>
      <xsd:attribute name="tracks" use="required" type="xsd:integer"/>
      <xsd:attribute name="loop" use="optional" type="xsd:string"/>
      <xsd:attribute name="loop-start" use="optional" type="xsd:integer"/>
      <xsd:attribute name="loop-end" use="optional" type="xsd:integer"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wave">
    <xsd:annotation>
      <xsd:documentation>
        Wave in a wavetable.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="index" use="required" type="xsd:integer"/>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
      <xsd:attribute name="uri" use="required" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="wavetable">
    <xsd:annotation>
      <xsd:documentation>
        List of waves.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="wave" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="buzztard">
    <xsd:annotation>
      <xsd:documentation>
        Toplevel elements for a buzztard song.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="meta" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="setup" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="sequence" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="wavetable" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Buzztrax/buzztrax/tests/songs/buzz1.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>one buzz generator</info>
    <name>buzz 1</name>
    <genre>dark-wave</genre>
    <bpm>120</bpm>
    <tpb>4</tpb>
    <bars>16</bars>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2005-09-20T22:10:56Z</change-dts>
  </meta>
  
  <setup zoom="1.0">
    <machines>
      <sink id="audio_sink">
        <properties>
         <property key="xpos" value="10" />
         <property key="ypos" value="40" />
        </properties>
        <globaldata name="volume" value="20"/>
        <globaldata name="bpm" value="145"/>
      </sink>
      
      <source id="gen" plugin-name="bml-DTMF-1" voices="0">
        <properties>
         <property key="xpos" value="10" />
         <property key="ypos" value="20" />
        </properties>
        <globaldata name="volume" value="1.0"/>
      </source>
    </machines>
    
    <wires>
      <wire src="gen" dst="audio_sink" gain="1.0" pan="-50"/>
    </wires>    
  </setup>
  
  <patterns>
    <pattern id="gen_beeps" machine="gen" name="beeps" length="16">
      <tick time="0">
        <voicedata name="Dial-Number" voice="0" value="1"/>
        <voicedata name="Sustain" voice ="0" value="200"/>
        <voicedata name="Volume" voice="0" value="200"/>
      </tick>
      <tick time="4">
        <voicedata name="Dial-Number" voice="0" value="2"/>
      </tick>
      <tick time="8">
        <voicedata name="Dial-Number" voice="0" value="3"/>
      </tick>
    </pattern>
  </patterns>
  
  <sequence>
    <labels>
      <label time="0" name="start"/>
      <label time="63" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="gen">
        <position time="0" pattern="gen_beeps"/>
        <position time="32" pattern="gen_beeps"/>
      </track>
    </tracks>
  </sequence>
  

</buzztard>

=== Buzztrax/buzztrax/tests/songs/buzz4.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>one buzz generator</info>
      <name>buzz 4</name>
    <genre>dark-wave</genre>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2005-09-20T22:10:56Z</change-dts>
    <bpm>120</bpm>
    <tpb>4</tpb>
    <bars>16</bars>
  </meta>
  
  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
      </machine>
      
      <machine type="source" id="gen" plugin-name="bml-Arguelles-GoaKick" voices="0">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <patterns>
          <pattern id="gen_beats" name="beats" length="16">
            <tick time="0">
              <globaldata name="Trigger" value="10"/>
              <globaldata name="Tone" value="40"/>
            </tick>
            <tick time="4"><globaldata name="Trigger" value="40"/></tick>
            <tick time="8"><globaldata name="Trigger" value="80"/></tick>
          </pattern>
        </patterns>
      </machine>
    </machines>
    
    <wires>
      <wire src="gen" dst="audio_sink" gain="1.0" panorama="-50"/>
    </wires>    
  </setup>
    
  <sequence length="96" tracks="1">
    <labels>
      <label time="0" name="start"/>
      <label time="95" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="gen">
        <position time="0" pattern="gen_beats"/>
        <position time="32" pattern="gen_beats"/>
        <position time="48" pattern="gen_beats"/>
        <position time="64" pattern="gen_beats"/>
        <position time="80" pattern="gen_beats"/>
      </track>
    </tracks>
  </sequence>
  
</buzztard>

=== Buzztrax/buzztrax/tests/songs/simple2.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>a sine followed by an amp, both playing patterns</info>
    <name>simple 2</name>
    <genre>dark-wave</genre>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2005-09-20T22:10:56Z</change-dts>
    <bpm>120</bpm>
    <tpb>4</tpb>
    <bars>16</bars>
  </meta>
  
  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
      </machine>
      
      <machine type="processor" id="amp1" plugin-name="volume">
        <properties>
          <property key="xpos" value="0.0"/>
          <property key="ypos" value="0.2"/>
        </properties>
        <patterns>
          <pattern id="amp1_fade" name="fade" length="16">
            <tick time= "0"><globaldata name="volume" value="1.0"/></tick>
            <tick time= "1"><globaldata name="volume" value="0.75"/></tick>
            <tick time= "2"><globaldata name="volume" value="0.5"/></tick>
            <tick time= "3"><globaldata name="volume" value="0.25"/></tick>
            <tick time= "4"><globaldata name="volume" value="1.0"/></tick>
            <tick time= "5"><globaldata name="volume" value="0.75"/></tick>
            <tick time= "6"><globaldata name="volume" value="0.5"/></tick>
            <tick time= "7"><globaldata name="volume" value="0.25"/></tick>
            <tick time= "8"><globaldata name="volume" value="1.0"/></tick>
            <tick time= "9"><globaldata name="volume" value="0.75"/></tick>
            <tick time="10"><globaldata name="volume" value="0.5"/></tick>
            <tick time="11"><globaldata name="volume" value="0.375"/></tick>
            <tick time="12"><globaldata name="volume" value="0.25"/></tick>
            <tick time="13"><globaldata name="volume" value="0.125"/></tick>
            <tick time="14"><globaldata name="volume" value="0.0"/></tick>
          </pattern>
        </patterns>
      </machine>
      
      <machine type="source" id="sine1" plugin-name="audiotestsrc" voices="0">
        <globaldata name="volume" value="1.0"/>
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <patterns>
          <pattern id="sine1_beeps" name="beeps" length="16">
            <tick time="0">
              <globaldata name="freq" value="440.0"/>
              <globaldata name="volume" value="1.0"/>
            </tick>
            <tick time="4">
              <globaldata name="freq" value="880.0"/>
              <globaldata name="volume" value="1.0"/>
            </tick>
            <tick time="8">
              <globaldata name="freq" value="1760.0"/>
              <globaldata name="volume" value="1.0"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
    </machines>
    
    <wires>
      <wire src="sine1" dst="amp1" gain="1.5"/>
      <wire src="amp1" dst="audio_sink" gain="1.0" panorama="-0.5"/>
    </wires>
  </setup>
  
  <sequence loop="on" loop-start="4" loop-end="32" length="64" tracks="2">
    <labels>
      <label time="0" name="start"/>
      <label time="63" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="sine1">
        <position time="0" pattern="sine1_beeps"/>
        <position time="32" pattern="sine1_beeps"/>
      </track>
      <track index="1" machine="amp1">
        <position time="0" pattern="amp1_fade"/>
        <position time="32" pattern="amp1_fade"/>
      </track>
    </tracks>
  </sequence>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/buzz9.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>one buzz generator</info>
    <name>buzz 1</name>
    <genre>dark-wave</genre>
    <bpm>120</bpm>
    <tpb>4</tpb>
    <bars>16</bars>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2005-09-20T22:10:56Z</change-dts>
  </meta>
  
  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
         <property key="xpos" value="0.7" />
         <property key="ypos" value="0.0" />
        </properties>
        <globaldata name="volume" value="20"/>
        <globaldata name="bpm" value="145"/>
      </machine>
      
      <machine type="source" id="beeps" plugin-name="bml-CyanPhase-DTMF-1" voices="0">
        <properties>
         <property key="xpos" value="-0.7" />
         <property key="ypos" value="0.2" />
        </properties>
        <globaldata name="volume" value="1.0"/>
        <patterns>
          <pattern id="beeps_beeps" machine="beeps" name="beeps" length="16">
            <tick time="0">
              <globaldata name="Dial-Number" value="1"/>
              <globaldata name="Sustain" value="30"/>
              <globaldata name="Volume" value="50"/>
            </tick>
            <tick time="4">
              <globaldata name="Dial-Number" value="2"/>
            </tick>
            <tick time="8">
              <globaldata name="Dial-Number" value="3"/>
            </tick>
          </pattern>
        </patterns>
      </machine>

      <machine type="source" id="beats" plugin-name="bml-Arguelles-GoaKick" voices="0">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
        <patterns>
          <pattern id="beats_beats" machine="beats" name="beats" length="16">
            <tick time="0">
              <globaldata name="Trigger" value="90"/>
              <globaldata name="Tone" value="40"/>
            </tick>
            <tick time="4"><globaldata name="Trigger" value="40"/></tick>
            <tick time="8"><globaldata name="Trigger" value="80"/></tick>
            <tick time="14"><globaldata name="Trigger" value="40"/></tick>
          </pattern>
        </patterns>
      </machine>

    </machines>
    
    <wires>
      <wire src="beeps" dst="audio_sink" gain="1.0" pan="-50"/>
      <wire src="beats" dst="audio_sink" gain="1.0" pan="50"/>
    </wires>    
  </setup>
    
  <sequence loop="off" length="64" tracks="2">
    <labels>
      <label time="0" name="start"/>
      <label time="63" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="beeps">
        <position time="0" pattern="beeps_beeps"/>
        <position time="32" pattern="beeps_beeps"/>
      </track>
      <track index="1" machine="beats">
        <position time="0" pattern="beats_beats"/>
        <position time="16" pattern="beats_beats"/>
        <position time="32" pattern="beats_beats"/>
        <position time="48" pattern="beats_beats"/>
      </track>
    </tracks>
  </sequence>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/melo2.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>a two voice melody</info>
    <name>melo 2</name>
    <genre>chip-music</genre>
    <bpm>120</bpm>
    <tpb>4</tpb>
    <bars>16</bars>
    <create-dts>2006-01-12T22:10:56Z</create-dts>
    <change-dts>2006-01-12T22:10:56Z</change-dts>
  </meta>
  
  <setup>
    <machines>
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.0"/>
        </properties>
        <globaldata name="volume" value="20"/>
        <globaldata name="bpm" value="145"/>
      </machine>
            
      <machine type="source" id="beep1" plugin-name="simsyn" voices="0">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <globaldata name="volume" value="1.0"/>
        <patterns>
          <pattern id="beep1::C-3_E-3_G-3" machine="beep1" name="C-3_E-3_G-3" length="16">
            <tick time="0">
              <globaldata name="note" value="c-3"/>
              <globaldata name="volume" value="1.0"/>
              <globaldata name="decay" value="0.25"/>
              <globaldata name="wave" value="2"/>
            </tick>
            <tick time="8">
              <globaldata name="note" value="e-3"/>
            </tick>
            <tick time="12">
              <globaldata name="note" value="g-3"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
    </machines>
    
    <wires>
      <wire src="beep1" dst="audio_sink" gain="1.0"/>
    </wires>    
  </setup>
    
  <sequence loop="off" length="64" tracks="2">
    <labels>
      <label time="0" name="start"/>
      <label time="63" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="beep1">
        <position time="0" pattern="beep1::C-3_E-3_G-3"/>
        <position time="32" pattern="beep1::C-3_E-3_G-3"/>
      </track>
      <track index="1" machine="audio_sink"/>
    </tracks>
  </sequence>

</buzztard>

=== Buzztrax/buzztrax/tests/songs/buzz2.xml
<?xml version="1.0" encoding="UTF-8"?>

<buzztard
  xmlns="http://www.buzztard.org/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
  xsd:noNamespaceSchemaLocation="buzztard.xsd">

  <meta>
    <info>a sine followed by an amp, both playing patterns</info>
    <name>simple 2</name>
    <genre>dark-wave</genre>
    <create-dts>2005-09-20T22:10:56Z</create-dts>
    <change-dts>2005-09-20T22:10:56Z</change-dts>
    <bpm>120</bpm>
    <tpb>4</tpb>
    <bars>16</bars>
  </meta>
  
  <setup>
    <machines>
      
      <machine type="sink" id="audio_sink">
        <properties>
          <property key="xpos" value="0.7"/>
          <property key="ypos" value="0.5"/>
        </properties>
      </machine>

      <machine type="processor" id="filter" plugin-name="bml-Elak-SVF">
        <properties>
          <property key="xpos" value="0.0"/>
          <property key="ypos" value="0.2"/>
        </properties>
      </machine>

      <machine type="source" id="guru2" plugin-name="bml-Arguelles-Guru-2" voices="0">
        <properties>
          <property key="xpos" value="-0.7"/>
          <property key="ypos" value="-0.5"/>
        </properties>
        <patterns>
          <pattern id="guru2_beeps" name="beeps" length="16">
            <tick time="0">
              <globaldata name="Note" value="c-3"/>
              <globaldata name="Length" value="80"/>
              <globaldata name="Hi-Volume" value="32766"/>
              <globaldata name="Flt-Decay" value="15"/>
            </tick>
            <tick time="4">
              <globaldata name="Note" value="e-3"/>
            </tick>
            <tick time="8">
              <globaldata name="Note" value="g-3"/>
            </tick>
            <tick time="10">
              <globaldata name="Note" value="g-3"/>
            </tick>
          </pattern>
        </patterns>
      </machine>
    </machines>
    
    <wires>
      <wire src="guru2" dst="filter" gain="1.0" panorama="-0.5"/>
      <wire src="filter" dst="audio_sink" gain="1.0" panorama="-0.5"/>
    </wires>    
  </setup>
  
  <sequence length="64" tracks="1">
    <labels>
      <label time="0" name="start"/>
      <label time="63" name="end"/>
    </labels>
    <tracks>
      <track index="0" machine="guru2">
        <position time="0" pattern="guru2_beeps"/>
        <position time="32" pattern="guru2_beeps"/>
      </track>
    </tracks>
  </sequence>
  
</buzztard>
